### ISSUE TITLE
Use GitHub Pages?

### ISSUE THREAD

**Issue by ghostofkendo** [martinbjeldbak/ultimate-beamer-theme-list#5]
Hi,

Now that the list has a reasonable amount of content, why not make it easier to find for people using search engines? It would be a shame if nobody uses it because they find other (less extensive) lists first.
[GitHub Pages](https://pages.github.com/) seems simple enough to set up.

**Comment by martinbjeldbak** [comment]
Interesting idea... it would even be possible to make a sortable, searchable list. I'll look into how quickly we can get GitHub pages like this up and running. Unfortunately it seems like a rewrite would be in order?

**Comment by ghostofkendo** [comment]
I would not know as I have never used GitHub Pages. Although, I do not think it would require a lot of rewriting. Starting with a simple page, quite similar to what we have know is good enough IMO.

**Comment by martinbjeldbak** [comment]
I used the auto page generator and got the following result: http://martinbjeldbak.com/ultimate-beamer-theme-list. It would require some HTML/JS tweaking in the gh-pages branch of this repo to get the table prettier, and possibly removing the download buttons, since this no one would benefit from it being downloadable. But it's a start... what do you think?

**Comment by ghostofkendo** [comment]
It is good start indeed.
I agree with you that removing the top download bar would be better.

**Comment by martinbjeldbak** [comment]
Done! 👍
